### PR TITLE
[FIX] web: only abandon records on discard without savepoint

### LINKED ISSUE #24547: Product names do not appear on the second page.
Impacted versions:  Odoo11

Steps to reproduce: Sales -> Orders -> Select an order from list -> Delivery -> Return -.> Stock Return 
                                Picking Wizard 

Current behavior: When I click return button in delivery form; If there are too many items on the product list, it goes to the second page. Everything is normal up to here but the names of the products on the second page do not appear. For this reason we can not get a refund.
 

Expected behavior: Product names appear on the second page if there are too many products

Video/Screenshot link (optional): 

issue1

issue2

### PR DESCRIPTION
**Pull request by alexkuhn**
### [FIX] web: only abandon records on discard without savepoint

Revision on https://github.com/odoo/odoo/commit/9a9da5763b38a3bce54e9c4870af0032e38cacc3

The intent of the commit above was to no abandon records in a list on
discard when these records have been created from a `default_get`.

Also, the `default_get` may also perform an `onchange` that could create
more records. The records from this `onchange` must also be included in
the "do not abandon" rule.

However, the rule was too relax, so that any following `onchanges` from
a user interaction was also considered into this rule. As a result, it was
not possible to abandon such records.

With this fix, we restrict the rule to `default_get` (already the case) and
only the `onchange` right after a `default_get`. Any record created on an
`onchange` from a user interaction after a `default_get` should be abandoned
on discard.

Representation of creating the list:

```
                               savepoint
   |----------|-----------|-------||--------|------->
 create   default_get  onchange1         onchange2
```

record in the list is created by default_get or onchange1
    => do not abandon on discard
record in the list is created by onchange2
    => abandon on discard

### CODE REVIEW

File: addons/web/static/src/js/views/basic/basic_model.js [hunk 1]
```diff
@@ -1971,16 +1971,20 @@ var BasicModel = AbstractModel.extend({
             ids.push(many2oneRecord.res_id);
             model = many2oneRecord.model;
         });
+        ids = _.uniq(ids);
         return this._rpc({
                 model: model,
                 method: 'name_get',
                 args: [ids],
```
Comment (aab-odoo) [inline addons/web/static/src/js/views/basic/basic_model.js]: args: [_.uniq(ids)],

File: addons/web/static/tests/fields/relational_fields_tests.js [hunk 2]
```diff
@@ -1237,6 +1237,97 @@ QUnit.module('relational_fields', {
...
+                if (args.method === 'name_get') {
+                    assert.deepEqual(args.args[0], _.uniq(args.args[0]),
+                        "should not have duplicates in name_get rpc");
+                }
+                return this._super.apply(this, arguments);
+            },
+        });
+
+        // trululu of 1st record shows 'first record', which is displayed name of trululu with id 1
+        var record1Trululu = form.$('tr.o_data_row').first().find('td.o_data_cell').first().next().text();
```
Comment (aab-odoo) [inline addons/web/static/tests/fields/relational_fields_tests.js]: first().next()? i'd try to find a simpler selector here

File: addons/web/static/tests/fields/relational_fields_tests.js [hunk 3]
```diff
@@ -1237,6 +1237,97 @@ QUnit.module('relational_fields', {
...
+        assert.strictEqual(record1Trululu, "first record",
+            "1st record should have the correct displayed name for trululu field");
+        // trululu of 2nd record shows 'first record', which is displayed name of trululu with id 1
+        var record2Trululu = form.$('tr.o_data_row').first().next().find('td.o_data_cell').first().next().text();
```
Comment (aab-odoo) [inline addons/web/static/tests/fields/relational_fields_tests.js]: same here

Comment (aab-odoo) [inline addons/web/static/tests/fields/relational_fields_tests.js]: actually you could check both with one assert like calling text() on a jquery nodeset of several cells (we do that at other places)

File: addons/web/static/src/js/views/basic/basic_model.js [hunk 4]
```diff
@@ -2466,7 +2470,16 @@ var BasicModel = AbstractModel.extend({
         var self = this;
         var def;
         if (list.static) {
-            def = this._readUngroupedList(list);
+            def = this._readUngroupedList(list).then(function () {
+                if (list.parentID && self.isNew(list.parentID)) {
+                    // list from a default_get, so fetch displayed_name for many2one fields
```
Comment (aab-odoo) [inline addons/web/static/src/js/views/basic/basic_model.js]: display_name

File: addons/web/static/src/js/views/basic/basic_model.js [hunk 5]
```diff
@@ -3034,6 +3047,23 @@ var BasicModel = AbstractModel.extend({
...
     },
+    /**
+     * Get many2one fields names in a datapoint. This is useful in order to
+     * fetch their names in the case of a default_get.
+     *
+     * @private
+     * @param {Object} datapoint a valid resource object
+     * @returns {string[]} list of field names that are many2one
+     */
+    _getMany2OneFieldNames: function (datapoint) {
```
Comment (aab-odoo) [inline addons/web/static/src/js/views/basic/basic_model.js]: shouldn't you call this function for the initial default_get as well? Otherwise, it is maybe no necessary...
