### PR TITLE
[Fix] point_of_sale: Button spamming create duplicates

### LINKED ISSUE #23919: [10.0] Creating customer in POS easily creates duplicates
Impacted versions: 10 community

Steps to reproduce: Create customer in POS clicking save button several times creates equally many customer cards without any sort of notification.

Expected behavior: Perhaps save button to be only clickable once after edit or even do Save and select as current client something? 

Video/Screenshot link (optional):
odoopos

### PR DESCRIPTION
**Pull request by Julien00859**
Spamming the save button when creating a new custommer in point-
of-sale create duplicate users. This PR disable the button once
clicked and re-enable it when all the processing is done.

opw-1895302

close #23919
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Julien00859** [comment]
@nim-odoo

**Comment by Julien00859** [comment]
This is not a regular button so I cannot add the `disabled` property on it. Also the `saved_client_details` method (called on a successful rpc) trigger an asynchronously action that changes the view from "create a new customer" to "edit the current one". So re-enabling the button *after* the view is changed is a better idea.

File: addons/point_of_sale/static/src/js/screens.js [hunk 1]
```diff
@@ -1254,6 +1258,7 @@ var ClientListScreenWidget = ScreenWidget.extend({
                 // has created, and reload_partner() must have loaded the newly created partner. 
                 self.display_client_details('hide');
             }
+            $(".client-details-contents").on('click','.button.save',function(){ self.save_client_details(partner); });
```
Comment (nim-odoo) [inline addons/point_of_sale/static/src/js/screens.js]: Actually, this could be in `always`, just in case `reload_partners` fails.

**Comment by Julien00859** [comment]
@nim-odoo
